 clc;
close all;
clear all;
n=0:99;
fs=10000;
fc=1000;
n_bits=10;
m1=randi([0,1],1,n_bits);
ma=repelem(m1,10);
c=cos(2*pi*(fc/fs)*n);
ask_modulated =ma.*c;
subplot(2,2,1);
plot(n,ma);
title("Message Signal");
subplot(2,2,2);
plot(n,c);
title("carrier signal");
subplot(2,2,3);
plot(n,ask_modulated);
title("ASK MODULATED SIGNAL");
ask_demodulation=ask_modulated./c;
subplot(2,2,4);
plot(n,ask_demodulation);
title("ASK DEMODULATION");
